version: "3.9"
services:
    web:
        build: .
        ports:
            - "8443:443"
        environment:
            CONNECTION_STRING: "Server=db;Database=master;User=sa;Password=Your_password123;"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"