name: Unit tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore ./IdentityApi/IdentityApi.sln

    - name: Build
      run: dotnet build ./IdentityApi/IdentityApi.sln --no-restore

    - name: Test
      run: dotnet test ./IdentityApi/IdentityApi.sln --filter Category=UnitTest --no-build --verbosity normal