name: Integration tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./IdentityApi.sln
    - name: Build
      run: dotnet build ./IdentityApi.sln --no-restore
    - name: Test
      run: dotnet test ./IdentityApi.sln --filter Category=IntegrationTest --no-build --verbosity normal